services:
  tf-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tf_executor_bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "18812:18812"
    volumes:
      - .:/app
      - mt5_wine_data:/root/.wine

volumes:
  mt5_wine_data:
    driver: local
